# Use a imagem oficial do SDK do .NET 7 para compilar a aplicação
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copie os arquivos do projeto para o contêiner
COPY . .

# Restaure as dependências e compile o projeto
RUN dotnet restore
RUN dotnet publish -c Release -o out

# Use a imagem oficial do ASP.NET 7 para a execução da aplicaçãodot
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

# Copie os arquivos publicados do estágio de compilação
COPY --from=build /app/out .

# Especifique o comando de inicialização da aplicação
ENTRYPOINT ["dotnet", "WebApi.dll"]